# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2 the first 10 terms will be:

# 1,2,3,5,8,13,21,34,55,89,...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms

#Fibanocci series
def fibannoci_num(n: int)-> [int]:
    a, b = 1,2
    fibb_series = [1]
    #for i in range(n):
    while b < n:
        a, b = b, a + b
        fibb_series.append(a)
    return fibb_series

print(fibannoci_num(100))

def even_fibannoci_num(n: int)-> [int]:
    a, b = 1,2
    fibb_series = []
    #for i in range(n):
    while b < n:
        a, b = b, a + b
        if a % 2 == 0:
            fibb_series.append(a)
    return fibb_series

print("Sum of even fibannoci numbers less than 4 million : ",sum(even_fibannoci_num(4000000)))